import { useEffect } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { Container, Row, Col, Navbar, Nav, NavDropdown, Form, FormControl, Button } from 'react-bootstrap'
import 'bootstrap/dist/css/bootstrap.min.css'

function MyApp({ Component, pageProps }) {
  const router = useRouter()
  useEffect(() => {
    import('bootstrap/dist/js/bootstrap.js')
  }, [])

  return (
    <>
      <Head>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <title>Demo Next.js</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Row className="justify-content-center">
          <Col md={10}>
            <header className="py-5">
              <h1>Header</h1>
            </header>
            <hr />
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md={10}>
            <Navbar bg="dark" variant="dark" className="px-3">
              <Navbar.Brand href="#">Navbar</Navbar.Brand>
              <Nav className="mr-auto">
                <Link href="/">
                  <a className={`nav-link ${router.pathname == '/' ? 'active' : ''}`}>Home</a>
                </Link>
                <Link href="/about">
                  <a className={`nav-link ${router.pathname == '/about' ? 'active' : ''}`}>About</a>
                </Link>
                <Link href="/contact">
                  <a className={`nav-link ${router.pathname == '/contact' ? 'active' : ''}`}>Contact</a>
                </Link>
              </Nav>
            </Navbar>
          </Col>
        </Row>
      </Container>

      <Container>
        <Row className="justify-content-center">
          <Col md={10}>
            <main className="py-3">
              <Component {...pageProps} />
            </main>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md={10}>
            <hr />
            <footer className="py-3">
              <h1>Footer</h1>
            </footer>
          </Col>
        </Row>
      </Container>
    </>
  )
}

export default MyApp
